### ISSUE TITLE
Qt Interface Design

### ISSUE THREAD

**Issue by MingDengEason** [FatigueDetecting/Fatigue_detecting#13]

**Comment by SR9898** [comment]
The functions in QT are mainly divided into two parts, one is the display function of the interface, which is responsible for the display position and size of the control, initialization of some variables, etc., and the other is mainly the slot function, which is responsible for responding to the received signal, Responsible for the implementation of specific functions. In this program, the number of cameras available to the device will be detected in the initialization phase, and the available camera numbers will be added to the interface for selection. The slot function corresponds to the implementation of the specific function. In the openCamera slot function, it is responsible for turning on the camera, turning on the 10ms timer, and turning on the two threads of reading and processing to run in the background. When the timer reaches 10ms, it will enter the showFrame slot function for processing. This function is responsible for reading the processed video frame and displaying the interface, and calling returnFrame to get the status.
