### ISSUE TITLE
Calibration BUG

### ISSUE THREAD

**Issue by smallssnow** [FatigueDetecting/Fatigue_detecting#22]

**Comment by SR9898** [comment]
After testing, when the "Open Camera" button is turned on, the system will automatically start to detect, which makes the button to check the detection function lose its function.

**Comment by SR9898** [comment]
By the way, there is not an accurate calibration function to call right now, it needs to be adjusted

**Comment by smallssnow** [comment]
Try to modify and increase the detection function switch

**Comment by smallssnow** [comment]
solve it
